def ScienceStory(name1, name2, name3):
    print("Science Ficrtion it is! lets get some info first...")
    verb = input("enter a verb")
    adjective = input("now enter an adjective")
    noun = input(" Now a noun")
    object = input("pick an object")
    print("That should be enough to get started and we can figure out the rest as we go..")
    print("A long time ago, in the far off galaxy of ___  was the glorious nation of the order of the [noun]. A once prosperous nation that was know for its ability to [adjective] prosperity for every man woman and child. In the days since the great [verb] war of 2376, the world has never been the same….")
    verb2 = input("enter a verb")
    adjective2 = input("now enter an adjective")
    noun2 = input(" Now a noun")